# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relearn_research', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='url',
            new_name='link',
        ),
    ]
