# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relearn_research', '0004_auto_20161221_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
